media:
  input: src/assets/images
  output: /images
  extensions: [svg, png, jpg, jpeg]
content:
  - name: posts
    label: Posts
    type: collection
    path: src/content/blog
    view:
      fields: [ title, draft, date ]
    fields:
      - { name: author, label: Author, type: string }
      - { name: pubDatetime, label: Date, type: date }
      - { name: modDatetime, label: Date, type: date }
      - { name: title, label: Title, type: string, required: true }
      - { name: ogImage, label: Title, type: string }
      - { name: slug, label: Slug, type: string }
      - { name: featured, label: Featured, type: boolean }
      - { name: draft, label: Draft, type: boolean }
      - { name: tags, label: Tags, type: string, list: true }
      - { name: description, label: Description, type: string }
      - { name: body, label: Body, type: rich-text }
  - name: leaders
    label: Leaders
    type: collection
    path: src/content/leaders
    view:
      fields: [ photo.src, name, position, sortOrder ]
      sort: [ sortOrder, name ]
      default:
        sort: sortOrder
        order: asc
    fields:
      - { name: name, label: Name, type: string, required: true }
      - { name: position, label: Position, type: string, required: true }
      - name: photo
        label: Photo
        type: object
        fields:
          - name: src
            label: Photo
            type: image
          - { name: alt, label: Alt Text, type: string }
      - { name: linkedin, label: LinkedIn URL, type: string, pattern: "^https://www\\.linkedin\\.com/.*$" }
      - { name: sortOrder, label: Sort Order, type: number, default: 999 }
      - { name: body, label: Bio, type: rich-text }
  - name: work
    label: Work
    type: collection
    path: src/content/work
    view:
      fields: [ title, client, summary, sortOrder ]
      sort: [ sortOrder, title ]
      default:
        sort: sortOrder
        order: asc
    fields:
      - { name: title, label: Title, type: string, required: true }
      - { name: client, label: Client, type: string, required: true }
      - { name: description, label: Full Description, type: string, required: true }
      - { name: summary, label: Card Summary, type: string, description: "A brief summary that appears on the work item card" }
      - name: image
        label: Image
        type: object
        required: false
        fields:
          - name: src
            label: Image
            type: image
            default: "/images/about-us.svg"
          - { name: alt, label: Alt Text, type: string, default: "Placeholder image" }
      - { name: sortOrder, label: Sort Order, type: number, default: 999 }
      - { name: body, label: Content, type: rich-text }
  - name: about
    label: About page
    type: file
    path: src/pages/about.md
    fields:
      - { name: layout, type: string, hidden: true, default: "../layouts/AboutLayout.astro" }
      - { name: title, label: Title, type: string }
      - name: about
        label: About Section
        type: object
        fields:
          - { name: title, label: Title, type: string }
          - { name: description, label: Description, type: text }
          - name: image
            label: Image
            type: object
            fields:
              - name: src
                label: Image
                type: image
              - { name: alt, label: Alt Text, type: string }
      - name: services
        label: Services
        type: object
        list: true
        fields:
          - { name: name, label: Service Name, type: string }
          - name: icon
            label: Icon
            type: image
          - name: items
            label: Service Items
            type: string
            list: true
      - name: values
        label: Values Section
        type: object
        fields:
          - { name: title, label: Title, type: string }
          - name: items
            label: Values
            type: object
            list: true
            fields:
              - { name: title, label: Title, type: string }
              - { name: description, label: Description, type: text }
      - name: leadership
        label: Leadership Section
        type: object
        fields:
          - { name: title, label: Title, type: string }
      - name: careers
        label: Careers Section
        type: object
        fields:
          - { name: title, label: Title, type: string }
          - { name: description, label: Description, type: text }
          - name: image
            label: Image
            type: object
            fields:
              - name: src
                label: Image
                type: image
              - { name: alt, label: Alt Text, type: string }
          - name: button
            label: Button
            type: object
            fields:
              - { name: href, label: Link, type: string }
              - { name: text, label: Text, type: string }
  - name: sbm
    label: SBM page
    type: file
    path: src/pages/sbm.md
    fields:
      - { name: layout, type: string, hidden: true, default: "../layouts/SbmLayout.astro" }
      - { name: title, label: Page Heading Text, type: string, required: true }
      - { name: description, label: Page Description, type: rich-text, required: true }
      - name: buttons
        label: SBM Link Buttons
        type: object
        list:
          min: 1
          max: 2
        fields:
          - { name: text, label: SBM Link Text, type: string, required: true }
          - { name: href, label: SBM Link URL, type: string, required: true }
  - name: contact
    label: Contact page
    type: file
    path: src/pages/contact.md
    fields:
      - { name: layout, type: string, hidden: true, default: "../layouts/ContactLayout.astro" }
      - { name: title, label: Title, type: string }
      - name: contact
        label: Contact Information
        type: object
        fields:
          - name: address
            label: Address
            type: object
            fields:
              - { name: street, label: Street Address, type: string }
              - { name: suite, label: Suite/Unit, type: string }
              - { name: city, label: City, type: string }
              - { name: state, label: State, type: string }
              - { name: zip, label: ZIP Code, type: string }
          - { name: phone, label: Phone Number, type: string }
          - { name: email, label: Email Address, type: string }
      - name: cta_career
        label: Careers CTA Section
        type: object
        fields:
          - { name: heading, label: Heading Text, type: string }
          - name: button
            label: Button
            type: object
            fields:
              - { name: text, label: Button Text, type: string }
              - { name: href, label: Button URL, type: string }
  - name: careers
    label: Careers page
    type: file
    path: src/pages/careers.md
    fields:
      - { name: layout, type: string, hidden: true, default: "../layouts/CareersLayout.astro" }
      - { name: title, label: Title, type: string }
      - { name: description, label: Description, type: string }
      - name: hero
        label: Hero Section
        type: object
        fields:
          - { name: heading, label: Heading, type: string }
          - { name: description, label: Description, type: text }
          - name: image
            label: Hero Image
            type: object
            fields:
              - name: src
                label: Image
                type: image
                description: "Select an image from the assets folder. The path will be automatically prefixed with /src/assets/images/"
              - { name: alt, label: Alt Text, type: string }
      - name: benefits
        label: Benefits Section
        type: object
        fields:
          - { name: heading, label: Heading, type: string }
          - name: items
            label: Benefits
            type: object
            list: true
            fields:
              - { name: title, label: Title, type: string }
              - { name: description, label: Description, type: text }
      - name: positions
        label: Open Positions Section
        type: object
        fields:
          - { name: heading, label: Heading, type: string }
          - name: items
            label: Positions
            type: object
            list: true
            fields:
              - { name: title, label: Position Title, type: string }
              - { name: type, label: Employment Type, type: string }
              - { name: location, label: Location, type: string }
              - { name: description, label: Description, type: text }
              - { name: link, label: Application Link, type: string }
      - name: teamPhotos
        label: Team Photos Section
        type: object
        fields:
          - { name: heading, label: Heading, type: string, default: "Team Photos" }
          - name: photos
            label: Photos
            type: object
            list: true
            fields:
              - name: image
                label: Photo
                type: image
              - { name: alt, label: Alt Text, type: string }
  - name: job-postings
    label: Job Postings
    type: collection
    path: src/content/careers
    view:
      fields: [ title, type, location, active ]
      sort: [ active, title ]
      default:
        sort: active
        order: desc
    fields:
      - { name: title, label: Job Title, type: string, required: true }
      - name: type
        label: Employment Type
        type: select
        options:
          - Full-time
          - Part-time
          - Contract
        required: true
      - { name: location, label: Location, type: string, required: true }
      - { name: department, label: Department, type: string, required: true }
      - { name: active, label: Active Posting, type: boolean, default: true }
      - { name: description, label: Short Description, type: string, required: true }
      - { name: responsibilities, label: Responsibilities, type: string, list: true }
      - { name: requirements, label: Requirements, type: string, list: true }
      - { name: benefits, label: Benefits, type: string, list: true }
      - { name: applicationUrl, label: Application URL, type: string }
      - { name: sortOrder, label: Sort Order, type: number, default: 999 }
      - { name: body, label: Full Description, type: rich-text }
  - name: home
    label: Home page
    type: file
    path: src/pages/home.md
    fields:
      - { name: layout, type: string, hidden: true, default: "../layouts/Layout.astro" }
      - { name: title, label: Title, type: string }
      - name: hero
        label: Hero Section
        type: object
        fields:
          - { name: title, label: Hero Title, type: string, required: true }
          - { name: description, label: Hero Description, type: text }
          - name: buttons
            label: Hero Buttons
            type: object
            list:
              min: 1
              max: 2
            fields:
              - { name: text, label: Button Text, type: string, required: true }
              - { name: href, label: Button URL, type: string, required: true }
              - { name: variant, label: Button Style, type: select, options: ["default", "outline"], default: "default" }
      - name: services
        label: Services Section
        type: object
        fields:
          - { name: title, label: Title, type: string }
          - name: items
            label: Services
            type: object
            list:
              max: 4
            fields:
              - { name: name, label: Service Name, type: string, required: true }
          - name: button
            label: Link Button
            type: object
            fields:
              - { name: text, label: Button Text, type: string, required: true }
              - { name: href, label: Button URL, type: string, required: true }
      - name: sbm
        label: SBM Section
        type: object
        fields:
          - { name: title, label: Title, type: string }
          - { name: description, label: Description, type: text }
          - name: categories
            label: Categories
            type: string
            list:
              min: 4
              max: 4
          - name: button
            label: Link Button
            type: object
            fields:
              - { name: text, label: Button Text, type: string, required: true }
              - { name: href, label: Button URL, type: string, required: true }
      - name: clients
        label: Clients Section
        type: object
        fields:
          - { name: title, label: Title, type: string }
          - name: images
            label: Client Logos
            type: object
            list:
              max: 12
            fields:
              - name: image
                label: Logo Image
                type: image
                required: true
              - { name: alt, label: Alt Text, type: string, required: true }
              - { name: width, label: Width, type: number, default: 150 }
              - { name: height, label: Height, type: number, default: 150 }
