media:
  input: src/assets/images
  output: /images
  extensions: [svg, png, jpg, jpeg]
content:
  - name: posts
    label: Posts
    type: collection
    path: src/content/blog
    view:
      fields: [ title, draft, date ]
    fields:
      - { name: author, label: Author, type: string }
      - { name: pubDatetime, label: Date, type: date }
      - { name: modDatetime, label: Date, type: date }
      - { name: title, label: Title, type: string, required: true }
      - { name: ogImage, label: Title, type: string }
      - { name: slug, label: Slug, type: string }
      - { name: featured, label: Featured, type: boolean }
      - { name: draft, label: Draft, type: boolean }
      - { name: tags, label: Tags, type: string, list: true }
      - { name: description, label: Description, type: string }
      - { name: body, label: Body, type: rich-text }
  - name: leaders
    label: Leaders
    type: collection
    path: src/content/leaders
    view:
      fields: [ photo.src, name, position, sortOrder ]
      sort: [ sortOrder, name ]
      default:
        sort: sortOrder
        order: asc
    fields:
      - { name: name, label: Name, type: string, required: true }
      - { name: position, label: Position, type: string, required: true }
      - name: photo
        label: Photo
        type: object
        fields:
          - name: src
            label: Photo
            type: image
          - { name: alt, label: Alt Text, type: string }
      - { name: linkedin, label: LinkedIn URL, type: string, pattern: "^https://www\\.linkedin\\.com/.*$" }
      - { name: sortOrder, label: Sort Order, type: number, default: 999 }
      - { name: body, label: Bio, type: rich-text }
  - name: about
    label: About page
    type: file
    path: src/pages/about.md
    fields:
      - { name: layout, type: string, hidden: true, default: "../layouts/AboutLayout.astro" }
      - { name: title, label: Title, type: string }
      - name: about
        label: About Section
        type: object
        fields:
          - { name: title, label: Title, type: string }
          - { name: description, label: Description, type: text }
          - name: image
            label: Image
            type: object
            fields:
              - name: src
                label: Image
                type: image
              - { name: alt, label: Alt Text, type: string }
      - name: services
        label: Services
        type: object
        list: true
        fields:
          - { name: name, label: Service Name, type: string }
          - name: icon
            label: Icon
            type: image
          - name: items
            label: Service Items
            type: string
            list: true
      - name: values
        label: Values Section
        type: object
        fields:
          - { name: title, label: Title, type: string }
          - name: items
            label: Values
            type: object
            list: true
            fields:
              - { name: title, label: Title, type: string }
              - { name: description, label: Description, type: text }
      - name: leadership
        label: Leadership Section
        type: object
        fields:
          - { name: title, label: Title, type: string }
      - name: careers
        label: Careers Section
        type: object
        fields:
          - { name: title, label: Title, type: string }
          - { name: description, label: Description, type: text }
          - name: image
            label: Image
            type: object
            fields:
              - name: src
                label: Image
                type: image
              - { name: alt, label: Alt Text, type: string }
          - name: button
            label: Button
            type: object
            fields:
              - { name: href, label: Link, type: string }
              - { name: text, label: Text, type: string }
  - name: sbm
    label: SBM page
    type: file
    path: src/pages/sbm.md
    fields:
      - { name: layout, type: string, hidden: true, default: "../layouts/SbmLayout.astro" }
      - { name: title, label: Title, type: string, required: true }
      - { name: description, label: Description, type: rich-text }
      - name: about
        label: About Section
        type: object
        required: true
        fields:
          - { name: title, label: Title, type: string, required: true }
          - { name: description, label: Description, type: rich-text, required: true }
      - name: buttons
        label: Buttons
        type: object
        list: true
        fields:
          - { name: text, label: Button Text, type: string, required: true }
          - { name: href, label: Button Link, type: string, required: true }
      - name: modules
        label: Modules Section
        type: object
        required: true
        fields:
          - { name: heading, label: Section Heading, type: string, required: true }
          - name: items
            label: Accordion Items
            type: object
            list: true
            fields:
              - { name: title, label: Item Title, type: string, required: true }
              - { name: content, label: Item Content, type: rich-text, required: true }
              - name: buttons
                label: Item Buttons
                type: object
                list: true
                fields:
                  - { name: text, label: Button Text, type: string, required: true }
                  - { name: href, label: Button Link, type: string, required: true }
