media:
  input: src/assets/images
  output: /images
  extensions: [svg, png, jpg, jpeg]
content:
  - name: job-postings
    label: Job Postings
    type: collection
    path: src/content/careers
    view:
      fields: [ title ]
    fields:
      - { name: title, label: Job Title, type: string, required: true }
