media:
  input: src/assets/images
  output: /images
  extensions: [svg, png, jpg, jpeg]
content:
  - name: job-postings
    label: Job Postings
    type: collection
    path: src/content/careers
    view:
      fields: [ title, location, active ]
      sort: [ active, title ]
      default:
        sort: active
        order: desc
    fields:
      - { name: title, label: Job Title, type: string, required: true }
      - name: type
        label: Employment Type
        type: select
        required: true
        options:
          values:
            - value: full-time
              label: Full-time
            - value: part-time
              label: Part-time
            - value: contract
              label: Contract
      - { name: location, label: Location, type: string, required: true }
      - { name: department, label: Department, type: string, required: true }
      - { name: active, label: Active Posting, type: boolean, default: true }
      - { name: description, label: Short Description, type: text, required: true }
      - { name: responsibilities, label: Responsibilities, type: string, list: true }
      - { name: requirements, label: Requirements, type: string, list: true }
      - { name: benefits, label: Benefits, type: string, list: true }
      - { name: applicationUrl, label: Application URL, type: string, pattern: "^https?://.*$" }
      - { name: sortOrder, label: Sort Order, type: number, default: 999 }
      - { name: body, label: Full Description, type: rich-text, required: true }
  - name: our-work
    label: Our Work
    type: collection
    path: src/content/work
    view:
      fields: [ title, client, summary, sortOrder ]
      sort: [ sortOrder, title ]
      default:
        sort: sortOrder
        order: asc
    fields:
      - { name: title, label: Title, type: string, required: true }
      - { name: client, label: Client, type: string, required: true }
      - { name: description, label: Full Description, type: text, required: true }
      - { name: summary, label: Card Summary, type: text, description: "A brief summary that appears on the work item card" }
      - name: image
        label: Image
        type: object
        required: false
        fields:
          - name: src
            label: Image
            type: image
            default: "/images/about-us.svg"
          - { name: alt, label: Alt Text, type: string, default: "Placeholder image" }
      - { name: sortOrder, label: Sort Order, type: number, default: 999 }
      - { name: body, label: Content, type: rich-text }
  - name: news
    label: News
    type: collection
    path: src/content/news
    view:
      fields: [ title, draft, date ]
    fields:
      - { name: author, label: Author, type: string, required: true }
      - { name: pubDatetime, label: Publication Date, type: date, required: true }
      - { name: modDatetime, label: Modified Date, type: date }
      - { name: title, label: Title, type: string, required: true }
      - { name: ogImage, label: Open Graph Image, type: string }
      - { name: slug, label: Slug, type: string }
      - { name: featured, label: Featured, type: boolean }
      - { name: draft, label: Draft, type: boolean }
      - { name: tags, label: Tags, type: string, list: true }
      - { name: description, label: Description, type: text }
      - { name: body, label: Body, type: rich-text, required: true }
  - name: leaders
    label: Leaders
    type: collection
    path: src/content/leaders
    view:
      fields: [ photo.src, name, position, sortOrder ]
      sort: [ sortOrder, name ]
      default:
        sort: sortOrder
        order: asc
    fields:
      - { name: name, label: Name, type: string, required: true }
      - { name: position, label: Position, type: string, required: true }
      - name: photo
        label: Photo
        type: object
        fields:
          - name: src
            label: Photo
            type: image
          - { name: alt, label: Alt Text, type: string }
      - { name: linkedin, label: LinkedIn URL, type: string, pattern: "^https://www\\.linkedin\\.com/.*$" }
      - { name: sortOrder, label: Sort Order, type: number, default: 999 }
      - { name: body, label: Bio, type: rich-text }
  - name: home
    label: Home page
    type: file
    path: src/pages/home.md
    fields:
      - { name: layout, type: string, hidden: true, default: "../layouts/Layout.astro" }
      - name: hero
        label: Hero Section
        type: object
        fields:
          - { name: title, label: Hero Text, type: string, required: true }
          - name: buttons
            label: Hero Buttons
            type: object
            list:
              min: 1
              max: 2
            fields:
              - { name: text, label: Button Text, type: string, required: true }
              - { name: href, label: Button URL, type: string, required: true }
              - name: variant
                label: Button Style
                type: select
                options:
                  values:
                    - value: default
                      label: Default
                    - value: outline
                      label: Outline                  
                default: default   
      - name: services
        label: Services Section
        type: object
        fields:
          - { name: title, label: Heading Text, type: string }
          - name: items
            label: Services
            type: object
            list:
              max: 4
            fields:
              - { name: name, label: Service Name, type: string, required: true }
          - name: button
            label: Learn More Link
            type: object
            fields:
              - { name: text, label: Link Text, type: string, required: true }
              - { name: href, label: Link URL, type: string, required: true }
      - name: sbm
        label: SBM Section
        type: object
        fields:
          - { name: title, label: Heading Text, type: string }
          - { name: description, label: Description, type: text }
          - name: categories
            label: Module Types
            type: string
            list:
              min: 4
              max: 4
          - name: button
            label: Learn More Link
            type: object
            fields:
              - { name: text, label: Link Text, type: string, required: true }
              - { name: href, label: Link URL, type: string, required: true }
      - name: clients
        label: Clients Section
        type: object
        fields:
          - { name: title, label: Heading Text, type: string, description: "Add up to 12 client logos" }
          - name: images
            label: Client Logos
            type: image
            list:
              max: 12
  - name: about
    label: About page
    type: file
    path: src/pages/about.md
    fields:
      - { name: layout, type: string, hidden: true, default: "../layouts/AboutLayout.astro" }
      - { name: title, label: Page Title, type: string, description: "This will be used as the page title in the browser", required: true }
      - name: about
        label: About Section
        type: object
        fields:
          - { name: title, label: Heading Text, type: string, description: "This will be used as the heading text in the about section", required: true }
          - { name: description, label: Description, type: text, description: "This will be used as the description in the about section", required: true }
          - name: image
            hidden: true
            label: Image
            type: object
            fields:
              - name: src
                label: Image
                type: image
              - { name: alt, label: Alt Text, type: string }
      - name: services
        label: Services
        type: object
        list:
          min: 4
          max: 4
        fields:
          - { name: name, label: Service Name, type: string, description: "This will be used as the service name in the about section", required: true }
          - name: icon
            label: Icon
            hidden: true
            type: object
            fields:
              - name: src
                label: Icon Image
                type: image
              - { name: alt, label: Alt Text, type: string }
          - name: items
            label: Service Items
            type: string
            list:
              min: 3
              max: 4
      - name: values
        label: Values Section
        type: object
        fields:
          - { name: title, label: Heading Text, type: string, description: "This will be used as the heading text in the values section", required: true }
          - name: items
            label: Values
            type: object
            list:
              min: 3
              max: 3
            fields:
              - { name: title, label: Value Name, type: string, description: "This will be used as the title in the values section", required: true }
              - { name: description, label: Description, type: text, description: "This will be used as the description in the values section", required: true }
      - name: leadership
        label: Leadership Section
        description: "This section is used to display the leadership team members"
        type: object
        fields:
          - { name: title, label: Title, type: string, description: "This will be used as the title in the leadership section", required: true }
      - name: careers
        label: Careers Section
        type: object
        fields:
          - { name: title, label: Heading Text, type: string, description: "This will be used as the heading text in the careers section", required: true }
          - { name: description, label: Description, type: text, description: "This will be used as the description in the careers section", required: true }
          - name: image
            hidden: true
            label: Image
            type: object
            fields:
              - name: src
                label: Image
                type: image
              - { name: alt, label: Alt Text, type: string }
          - name: button
            label: Button
            type: object
            fields:
              - { name: href, label: Button URL, type: string, required: true }
              - { name: text, label: Button Text, type: string, required: true }
  - name: sbm
    label: SBM page
    type: file
    path: src/pages/sbm.md
    fields:
      - { name: layout, type: string, hidden: true, default: "../layouts/SbmLayout.astro" }
      - { name: title, label: Page Title, type: string, description: "This will be used as the page title in the browser", required: true }
      - { name: description, label: Page Description, type: rich-text, required: true }
      - name: buttons
        label: SBM Link Buttons
        type: object
        list:
          min: 1
          max: 2
        fields:
          - { name: text, label: SBM Link Text, type: string, required: true }
          - { name: href, label: SBM Link URL, type: string, required: true }
      - name: modules
        label: Marketplace Modules
        type: object
        fields:
          - { name: heading, label: Section Heading, type: string, required: true }
          - name: items
            label: Module Items
            type: object
            list: true
            fields:
              - { name: title, label: Module Title, type: string, required: true }
              - { name: content, label: Module Content, type: text, required: true }
              - name: buttons
                label: Module Buttons
                type: object
                list:
                  max: 3
                fields:
                  - { name: text, label: Button Text, type: string, required: true }
                  - { name: href, label: Button URL, type: string, required: true, pattern: "^https?://.*$" }
  - name: work
    label: Work page
    type: file
    path: src/pages/work.md
    fields:
      - { name: layout, type: string, hidden: true, default: "../layouts/WorkLayout.astro" }
      - { name: title, label: Page Title, type: string, description: "This will be used as the page title in the browser", required: true }      
      - { name: description, label: Page Description, type: text }                  
  - name: contact
    label: Contact page
    type: file
    path: src/pages/contact.md
    fields:
      - { name: layout, type: string, hidden: true, default: "../layouts/ContactLayout.astro" }
      - { name: title, label: Page Title, type: string, description: "This will be used as the page title in the browser", required: true }
      - name: contact
        label: Contact Information
        type: object
        fields:
          - name: address
            label: Address
            type: object
            fields:
              - { name: street, label: Street Address, type: string, required: true }
              - { name: suite, label: Suite/Unit, type: string }
              - { name: city, label: City, type: string, required: true }
              - { name: state, label: State, type: string, required: true }
              - { name: zip, label: ZIP Code, type: string, required: true }
          - { name: phone, label: Phone Number, type: string, required: true }
          - { name: email, label: Email Address, type: string, required: true, pattern: "^[\\w-\\.]+@([\\w-]+\\.)+[\\w-]{2,4}$" }
      - name: cta_career
        label: Careers CTA Section
        type: object
        fields:
          - { name: heading, label: Heading Text, type: string }
          - name: button
            label: CTA Button
            required: true
            type: object
            fields:
              - { name: text, label: Button Text, type: string, required: true }
              - { name: href, label: Button URL, type: string, required: true }
  - name: careers
    label: Careers page
    type: file
    path: src/pages/careers.md
    fields:
      - { name: layout, type: string, hidden: true, default: "../layouts/CareersLayout.astro" }
      - { name: title, label: Page Title, type: string, description: "This will be used as the page title in the browser", required: true }
      - { name: description, label: Description, type: text }
      - name: hero
        label: Hero Section
        type: object
        fields:
          - { name: heading, label: Heading, type: string, required: true }
          - { name: description, label: Description, type: text, required: true }
          - name: image
            label: Hero Image
            hidden: true
            type: object
            fields:
              - name: src
                label: Image
                type: image
                description: "Select an image from the assets folder. The path will be automatically prefixed with /src/assets/images/"
              - { name: alt, label: Alt Text, type: string }
      - name: benefits
        label: Benefits Section
        type: object
        fields:
          - { name: heading, label: Heading, type: string, required: true }
          - name: items
            label: Benefits
            type: object
            list: true
            fields:
              - { name: title, label: Title, type: string, required: true }
              - { name: description, label: Description, type: text, required: true }
      - name: positions
        label: Open Positions Section
        type: object
        fields:
          - { name: heading, label: Heading, type: string, required: true }
      - name: teamPhotos
        label: Team Photos Section
        type: object
        fields:
          - { name: heading, label: Heading, type: string, default: "Team Photos" }
          - name: photos
            label: Photos
            type: object
            list: true
            fields:
              - name: image
                label: Photo
                type: image
              - { name: alt, label: Alt Text, type: string }
  - name: site-config
    label: Site Configuration
    type: file
    path: src/config.ts
    fields:
      - name: SITE
        label: Site Settings
        type: object
        fields:
          - { name: website, label: Website URL, type: string, pattern: "^https?://.*$", description: "The deployed domain of your website" }
          - { name: author, label: Author, type: string }
          - { name: desc, label: Description, type: text }
          - { name: title, label: Site Title, type: string }
          - { name: ogImage, label: Default Social Image, type: string }
          - { name: lightAndDarkMode, label: Enable Light/Dark Mode, type: boolean }
          - { name: postPerPage, label: Posts Per Page, type: number }
          - { name: scheduledPostMargin, label: Scheduled Post Margin (ms), type: number }
      - name: LOCALE
        label: Locale Settings
        type: object
        fields:
          - { name: lang, label: Language Code, type: string }
          - { name: langTag, label: Language Tags, type: string, list: true }
      - name: LOGO_IMAGE
        label: Logo Settings
        type: object
        fields:
          - { name: enable, label: Enable Logo, type: boolean }
          - { name: svg, label: Is SVG, type: boolean }
          - { name: width, label: Width, type: number }
          - { name: height, label: Height, type: number }
      - name: SOCIALS
        label: Social Media Links
        type: object
        list: true
        fields:
          - { name: name, label: Platform Name, type: string }
          - { name: href, label: URL, type: string, pattern: "^https?://.*$" }
          - { name: linkTitle, label: Link Title, type: string }
          - { name: active, label: Active, type: boolean }
