media:
  input: public
  output: /
content:
  - name: posts
    label: Posts
    type: collection
    path: src/content/blog
    view:
      fields: [ title, draft, date ]
    fields:
      - { name: author, label: Author, type: string }
      - { name: pubDatetime, label: Date, type: date }
      - { name: modDatetime, label: Date, type: date }
      - { name: title, label: Title, type: string, required: true }
      - { name: ogImage, label: Title, type: string }
      - { name: slug, label: Slug, type: string }
      - { name: featured, label: Featured, type: boolean }
      - { name: draft, label: Draft, type: boolean }
      - { name: tags, label: Tags, type: string, list: true }
      - { name: description, label: Description, type: string }
      - { name: body, label: Body, type: rich-text }
  - name: about
    label: About page
    type: file
    path: src/pages/about.md
    fields:
      - { name: layout, type: string, hidden: true, default: "../layouts/AboutLayout.astro" }
      - { name: title, label: Title, type: string }
      - name: about
        label: About Section
        type: object
        fields:
          - { name: title, label: Title, type: string }
          - { name: description, label: Description, type: text }
      - name: services
        label: Services
        type: object
        list: true
        fields:
          - { name: name, label: Service Name, type: string }
          - { name: icon, label: Icon Name, type: string }
          - name: items
            label: Service Items
            type: string
            list: true
      - name: careers
        label: Careers Section
        type: object
        fields:
          - { name: title, label: Title, type: string }
          - { name: description, label: Description, type: text }
          - name: image
            label: Image
            type: object
            fields:
              - { name: src, label: Source, type: string }
              - { name: alt, label: Alt Text, type: string }
