media:
  input: src/assets/images
  output: /images
  extensions: [svg, png, jpg, jpeg]
content:
  - name: job-postings
    label: Job Postings
    type: collection
    path: src/content/careers
    view:
      fields: [ title, type, location, active, responsibilities, requirements, benefits ]
      sort: [ active, title ]
      default:
        sort: active
        order: desc
    fields:
      - { name: title, label: Job Title, type: string, required: true }
      - name: type
        label: Employment Type
        type: select
        options:
          full-time: Full-time
          part-time: Part-time
          contract: Contract
        required: true
      - { name: location, label: Location, type: string, required: true }
      - { name: department, label: Department, type: string, required: true }
      - { name: active, label: Active Posting, type: boolean, default: true }
      - { name: description, label: Short Description, type: text, required: true }
      - { name: responsibilities, label: Responsibilities, type: string, list: true }
      - { name: requirements, label: Requirements, type: string, list: true }
      - { name: benefits, label: Benefits, type: string, list: true }
      - { name: applicationUrl, label: Application URL, type: string, pattern: "^https?://.*$" }
      - { name: sortOrder, label: Sort Order, type: number, default: 999 }
      - { name: body, label: Full Description, type: rich-text, required: true }
